---
- name: Enforce Service Health and show failed-aware YAML
  hosts: all
  gather_facts: false
  vars:
    services:
      - rsyslog.service
      - zabbix-agent2.service

  tasks:

    - name: Ensure services are started
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      loop: "{{ services }}"
      register: svc_status
      ignore_errors: yes

    - name: Gather detailed systemctl status
      ansible.builtin.command:
        cmd: "systemctl show {{ item }} --no-pager --property=ActiveState,SubState,LoadState,Result,UnitFileState"
      loop: "{{ services }}"
      register: svc_detailed
      ignore_errors: yes

    - name: Transform each service output to dict
      set_fact:
        service_status_summary: >-
          {{
            dict(
              svc_detailed.results | 
              map(attribute='stdout_lines') |
              map('map', 'split', '=', 1) |
              map('map', 'trim') |
              map('community.general.items2dict_list') |
              zip(services) |
              map('reverse') |
              list
            )
          }}
