---
- name: Enforce Service Health and show failed-aware YAML
  hosts: all
  gather_facts: false
  vars:
    services:
      - rsyslog.service
      - zabbix-agent2.service

  tasks:

    - name: Gather systemd service status
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      loop: "{{ services }}"
      register: svc_status
      ignore_errors: yes

    - name: Gather detailed systemctl status
      ansible.builtin.command:
        cmd: "systemctl show {{ item }} --no-pager --property=ActiveState,SubState,LoadState,Result,UnitFileState"
      loop: "{{ services }}"
      register: svc_detailed
      ignore_errors: yes

    - name: Gather recent journal logs for failed services
      ansible.builtin.command:
        cmd: "journalctl -u {{ item }} -n 5 --no-pager"
      loop: "{{ services }}"
      register: svc_journal
      ignore_errors: yes

    - name: Build clean YAML service status
      set_fact:
        service_status_summary: >-
          {{
            dict(
              svc_detailed.results | map('extract', ['stdout_lines']) | map('map','split','=',1') | map('map','trim') | map('map','list') | map('items2dict') | zip(services) | map('reverse') | list
            )
          }}

    - name: Show final service status in clean YAML
      ansible.builtin.debug:
        var: service_status_summary

    - name: Alert if any service is failed
      ansible.builtin.debug:
        msg: "⚠️ Service {{ item.key }} has failed! ActiveState={{ item.value.ActiveState }}, SubState={{ item.value.SubState }}"
      loop: "{{ service_status_summary|dict2items }}"
      when: item.value.ActiveState not in ['active', 'activating'] or item.value.Result != 'success'
