---
- name: Enforce Service Health and show YAML safely
  hosts: all
  gather_facts: false
  vars:
    services:
      - rsyslog.service
      - zabbix-agent2.service

  tasks:

    - name: Ensure services are started and enabled (ignore errors)
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"
      ignore_errors: yes

    - name: Gather systemctl show output for each service
      ansible.builtin.command:
        cmd: "systemctl show {{ item }} --no-pager"
      loop: "{{ services }}"
      ignore_errors: yes
      register: svc_detailed

    - name: Convert stdout_lines to dict per service
      set_fact:
        service_status_summary: "{{ service_status_summary|default({}) | combine({item.item: dict((line.split('=',1)|map('trim')|list) for line in item.stdout_lines if '=' in line)}) }}"
      loop: "{{ svc_detailed.results }}"

    - name: Add FAILED/OK flag
      set_fact:
        service_status_summary: >-
          {{
            service_status_summary | dict2items
            | map('combine', {"value": item.value | combine({"Status": "FAILED" if item.value.ActiveState != "active" else "OK"})})
            | items2dict
          }}

    - name: Show final service status
      ansible.builtin.debug:
        var: service_status_summary
