---
- name: Enforce Service Health and show real systemd status in YAML
  hosts: all
  gather_facts: no
  vars:
    services:
      - rsyslog.service
      - zabbix-agent2.service

  tasks:

    - name: Gather systemd service status
      command: systemctl show {{ item }} --no-page
      register: svc_detailed
      loop: "{{ services }}"

    - name: Transform systemctl output to dict per service
      set_fact:
        service_status_summary: >-
          {{
            dict(
              services | zip(
                svc_detailed.results | map(attribute='stdout_lines') | map('map','split','=',1') | map('map','trim') | map('items2dict')
              )
            )
          }}

    - name: Highlight failed/activating services
      debug:
        msg: >-
          {{
            service_status_summary | dict2items | 
            map('combine', {'status': ("FAILED" if item.value.ActiveState != "active" else "OK")}) | items2dict
          }}
