---
- name: Enforce Service Health and show clean YAML (failed-aware)
  hosts: all
  become: yes
  gather_facts: no

  vars:
    services_to_check:
      - rsyslog.service
      - zabbix-agent2.service

  tasks:

    - name: Gather initial service facts
      service_facts:

    - name: Try to start and enable services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services_to_check }}"
      ignore_errors: yes
      register: systemd_result

    - name: Refresh service facts after start/enable
      service_facts:

    - name: Build clean YAML service status
      set_fact:
        service_status_summary: >-
          {{
            service_status_summary | default({}) | combine({
              item: {
                'enabled': (
                  ansible_facts.services[item].enabled | default('absent')
                  if item in ansible_facts.services else 'absent'
                ),
                'state': (
                  ansible_facts.services[item].state | default(
                    (systemd_result.results[loop.index0].failed | ternary('failed','absent'))
                  )
                  if item in ansible_facts.services else
                    (systemd_result.results[loop.index0].failed | ternary('failed','absent'))
                ),
                'active_state': (
                  ansible_facts.services[item].active_state | default(
                    (systemd_result.results[loop.index0].failed | ternary('failed','absent'))
                  )
                  if item in ansible_facts.services else
                    (systemd_result.results[loop.index0].failed | ternary('failed','absent'))
                )
              }
            })
          }}
      loop: "{{ services_to_check }}"

    - name: Show final clean YAML
      debug:
        var: service_status_summary
        verbosity: 0
