---
- name: Enforce Service Health with clean YAML output
  hosts: all
  become: yes
  gather_facts: no

  vars:
    services_to_check:
      - rsyslog
      - zabbix-agent2

  tasks:

    - name: Check if service exists
      command: systemctl status {{ item }}
      register: service_check
      ignore_errors: yes
      loop: "{{ services_to_check }}"
      changed_when: false

    - name: Ensure services are enabled and started
      systemd:
        name: "{{ item.item }}"
        enabled: yes
        state: started
      loop: "{{ service_check.results }}"
      when: item.rc == 0
      register: service_result

    - name: Collect final service facts
      service_facts:

    - name: Build YAML-friendly output
      set_fact:
        service_status_summary: "{{ service_status_summary|default({}) | combine({ item: { 'enabled': ansible_facts.services[item].enabled, 'state': ansible_facts.services[item].state, 'active_state': ansible_facts.services[item].active_state } }) }}"
      loop: "{{ services_to_check }}"

    - name: Show service status as clean YAML
      debug:
        var: service_status_summary
