---
- name: Enforce Service Health and show YAML safely
  hosts: all
  gather_facts: no
  vars:
    services:
      - rsyslog.service
      - zabbix-agent2.service

  tasks:

    - name: Ensure services are started
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"
      ignore_errors: yes

    - name: Gather systemctl show output for each service
      ansible.builtin.command:
        cmd: "systemctl show {{ item }} --no-pager"
      register: svc_detailed
      loop: "{{ services }}"
      ignore_errors: yes

    - name: Build clean YAML service status safely
      set_fact:
        service_status_summary: >-
          {{
            dict(
              services | zip(
                svc_detailed.results | map(attribute='stdout_lines') | map('map', 'split', '=', 1) | map('map', 'trim') | map('items2dict_safe')
              )
            )
          }}

    - name: Show final clean YAML
      ansible.builtin.debug:
        var: service_status_summary

# Custom filter plugin items2dict_safe (roles/filter_plugins/items2dict_safe.py)
# Bu filter list of lists alır ve dict’e çevirir, hatalı veri olsa bile playbook fail olmaz
# İçeriği:
# def items2dict_safe(l):
#     try:
#         return dict(l)
#     except:
#         return {"_error": "could not convert to dict"}
# class FilterModule(object):
#     def filters(self):
#         return {"items2dict_safe": items2dict_safe}
