---
- name: Enforce Service Health and show clean YAML (fixed loop)
  hosts: all
  become: yes
  gather_facts: no

  vars:
    services_to_check:
      - rsyslog.service
      - zabbix-agent2.service

  tasks:

    - name: Gather initial service facts
      service_facts:

    - name: Try to start and enable services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services_to_check }}"
      ignore_errors: yes
      register: systemd_result

    - name: Refresh service facts after start/enable
      service_facts:

    - name: Build clean YAML service status
      set_fact:
        service_status_summary: "{{ service_status_summary | default({}) | combine({ item: { 'enabled': enabled_val, 'state': state_val, 'active_state': active_val }}) }}"
      loop: "{{ services_to_check }}"
      loop_control:
        loop_var: item
      vars:
        svc: "{{ ansible_facts.services[item] | default({}) }}"
        res: "{{ (systemd_result.results | selectattr('item','equalto',item) | list)[0] }}"
        enabled_val: "{{ svc.enabled | default('absent') }}"
        state_val: "{{ svc.state | default(res.failed | ternary('failed','absent')) }}"
        active_val: "{{ svc.active_state | default(res.failed | ternary('failed','absent')) }}"

    - name: Show final clean YAML
      debug:
        var: service_status_summary
