---
- name: Enforce Service Health and show failed-aware YAML
  hosts: all
  gather_facts: no
  vars:
    services_to_check:
      - rsyslog.service
      - zabbix-agent2.service
  tasks:

    - name: Gather systemd service status
      ansible.builtin.shell: systemctl show {{ item }} --no-page
      loop: "{{ services_to_check }}"
      register: svc_status
      ignore_errors: yes

    - name: Gather recent journal logs for failed services
      ansible.builtin.shell: "journalctl -u {{ item }} -n 20 --no-pager"
      loop: "{{ services_to_check }}"
      register: svc_logs
      ignore_errors: yes

    - name: Build fail-aware YAML-friendly dict
      set_fact:
        service_status_summary: "{{ service_status_summary | default({}) | combine({ item: {
          'LoadState': (svc_status.results[loop.index0].stdout_lines | select('search','LoadState') | first).split('=')[1] | default('unknown') | trim,
          'ActiveState': (svc_status.results[loop.index0].stdout_lines | select('search','ActiveState') | first).split('=')[1] | default('unknown') | trim,
          'SubState': (svc_status.results[loop.index0].stdout_lines | select('search','SubState') | first).split('=')[1] | default('unknown') | trim,
          'Result': (svc_status.results[loop.index0].stdout_lines | select('search','Result') | first).split('=')[1] | default('unknown') | trim,
          'UnitFileState': (svc_status.results[loop.index0].stdout_lines | select('search','UnitFileState') | first).split('=')[1] | default('unknown') | trim,
          'status': "FAILED" if ((svc_status.results[loop.index0].stdout_lines | select('search','ActiveState') | first).split('=')[1] != 'active') or
                               ((svc_status.results[loop.index0].stdout_lines | select('search','Result') | first).split('=')[1] == 'exit-code') else "OK",
          'recent_logs': svc_logs.results[loop.index0].stdout if ((svc_status.results[loop.index0].stdout_lines | select('search','ActiveState') | first).split('=')[1] != 'active') or
                                                              ((svc_status.results[loop.index0].stdout_lines | select('search','Result') | first).split('=')[1] == 'exit-code') else ""
        }}) }}"
      loop: "{{ services_to_check }}"
      loop_control:
        loop_var: item

    - name: Show final clean YAML
      ansible.builtin.debug:
        var: service_status_summary
