---
- name: Enforce Service Health and show YAML safely
  hosts: all
  gather_facts: false
  vars:
    services:
      - rsyslog.service
      - zabbix-agent2.service

  tasks:

    - name: Ensure services are started and enabled (ignore errors)
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"
      ignore_errors: yes
      register: start_results

    - name: Gather systemctl show output for each service
      ansible.builtin.command:
        cmd: "systemctl show {{ item }} --no-pager"
      loop: "{{ services }}"
      ignore_errors: yes
      register: svc_detailed

    - name: Build clean YAML service status safely
      set_fact:
        service_status_summary: >-
          {{
            dict(
              services | zip(
                svc_detailed.results | map(attribute='stdout_lines') | map('community.general.list_to_dict','=',0)
              )
            )
          }}

    - name: Highlight failed services
      set_fact:
        service_status_summary: >-
          {{
            service_status_summary | dict2items
            | map(
                'combine', 
                {"value": item.value | combine({"Status": "FAILED" if item.value.ActiveState != "active" else "OK"})}
              )
            | items2dict
          }}

    - name: Show final service status
      ansible.builtin.debug:
        var: service_status_summary
