---
- name: Enforce Service Health and show real systemd status in YAML
  hosts: all
  become: yes
  gather_facts: no

  vars:
    services_to_check:
      - rsyslog.service
      - zabbix-agent2.service

  tasks:

    - name: Gather real systemd status for each service
      command: systemctl show "{{ item }}" --no-page --all --property=ActiveState,SubState,LoadState,UnitFileState,Result
      loop: "{{ services_to_check }}"
      loop_control:
        loop_var: item
      register: svc_status
      ignore_errors: yes

    - name: Build clean YAML service status from systemctl
      set_fact:
        service_status_summary: "{{ service_status_summary | default({}) | combine({ item: { 
          'load_state': (svc_output.LoadState | default('absent')),
          'active_state': (svc_output.ActiveState | default('absent')),
          'sub_state': (svc_output.SubState | default('absent')),
          'enabled': (svc_output.UnitFileState | default('absent')),
          'result': (svc_output.Result | default('none'))
        }}) }}"
      loop: "{{ services_to_check }}"
      loop_control:
        loop_var: item
      vars:
        svc_output: >-
          {{
            dict(
              (svc_status.results | selectattr('item','equalto',item) | map(attribute='stdout_lines') | list | first | map('split', '=') | map('map','trim') | map('list') | list) | items2dict
            )
          }}

    - name: Show final clean YAML with real systemd status
      debug:
        var: service_status_summary
