- name: Enforce Service Health and show YAML safely
  hosts: all
  gather_facts: false
  vars:
    services:
      - rsyslog.service
      - zabbix-agent2.service

  tasks:

    - name: Ensure services are started and enabled (ignore errors)
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"
      ignore_errors: yes
      register: service_start_results

    - name: Gather systemctl show output for each service
      ansible.builtin.command:
        cmd: "systemctl show {{ item }} --no-pager --property=Id,ActiveState,SubState,LoadState,UnitFileState,MainPID,Result,ExecMainStatus,NRestarts"
      loop: "{{ services }}"
      ignore_errors: yes
      register: svc_detailed
      changed_when: false

    - name: Display service status
      ansible.builtin.debug:
        msg: 
          - "══════════════════════════════════"
          - "SERVİS: {{ item.key }}"
          - "══════════════════════════════════"
          - "Durum    : {{ '✅ OK' if item.value.ActiveState == 'active' else '❌ HATA' }}"
          - "Aktif    : {{ item.value.ActiveState }}"
          - "Alt Durum: {{ item.value.SubState }}"
          - "PID      : {{ item.value.MainPID }}"
          - "Restart  : {{ item.value.NRestarts }} kez"
          - "Sonuç    : {{ item.value.Result }}"
          - "Exit Code: {{ item.value.ExecMainStatus }}"
          - "══════════════════════════════════"
      loop: "{{ service_status_summary | dict2items }}"
      when: service_status_summary is defined
