---
- name: Enforce Service Health with clean YAML output
  hosts: all
  become: yes
  gather_facts: no

  vars:
    services_to_check:
      - rsyslog.service
      - zabbix-agent2.service

  tasks:

    - name: Gather all service facts
      service_facts:

    - name: Build YAML-friendly service status
      set_fact:
        service_status_summary: >-
          {{
            service_status_summary | default({}) | combine({
              item: {
                'enabled': (ansible_facts.services[item].enabled | default('absent')),
                'state': (ansible_facts.services[item].state | default('absent')),
                'active_state': (ansible_facts.services[item].active_state | default('absent'))
              }
            })
          }}
      loop: "{{ services_to_check }}"

    - name: Ensure services are enabled and started if they exist
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services_to_check }}"
      ignore_errors: yes

    - name: Show final service status in clean YAML
      debug:
        var: service_status_summary
